# Generated by Django 5.2.5 on 2025-08-28 13:33

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'schema_pp_internal"."metrics',
            },
        ),
        migrations.CreateModel(
            name='OKPD2Codifier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('description', models.TextField()),
                ('parent_id', models.IntegerField()),
            ],
            options={
                'db_table': 'schema_pp_official"."okpd2_codifier',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okpd2_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('regions_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('metrics', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('completed', models.IntegerField(default=-1)),
                ('progress', models.IntegerField(default=0)),
                ('writed', models.BooleanField(default=False)),
                ('data_file', models.URLField(default=None, null=True)),
                ('error_msg', models.TextField(null=True)),
            ],
            options={
                'db_table': 'schema_pp_internal"."processes',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(max_length=50)),
                ('region_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'schema_pp_internal"."regions',
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'schema_pp_internal"."segments',
            },
        ),
        migrations.CreateModel(
            name='IntermediateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contracts_count', models.IntegerField(default=0)),
                ('offers_total', models.IntegerField(default=0)),
                ('offers_active', models.IntegerField(default=0)),
                ('okpd2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics_pp.okpd2codifier')),
                ('process_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics_pp.process')),
            ],
            options={
                'db_table': 'schema_pp_internal"."intermediate_data',
            },
        ),
        migrations.CreateModel(
            name='RegionCodifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(max_length=50)),
                ('region_name', models.CharField(max_length=255)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statistics_pp.region')),
            ],
            options={
                'db_table': 'schema_pp_official"."regions_codifier',
            },
        ),
        migrations.CreateModel(
            name='OKPD2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('segments', models.ManyToManyField(to='statistics_pp.segment')),
            ],
            options={
                'db_table': 'schema_pp_internal"."okpd2',
            },
        ),
    ]
