# Generated by Django 5.2.5 on 2025-08-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_pp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okpd2codifier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
