# Generated by Django 5.2.5 on 2025-08-28 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_pp', '0002_alter_okpd2codifier_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='regions_ids',
            new_name='region_ids',
        ),
    ]
