# Generated by Django 5.2.5 on 2025-08-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_pp', '0003_rename_regions_ids_process_region_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='writed',
            field=models.IntegerField(default=0),
        ),
    ]
