# Generated by Django 5.2.5 on 2025-08-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_pp', '0004_alter_process_writed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intermediatedata',
            name='contracts_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='intermediatedata',
            name='offers_active',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='intermediatedata',
            name='offers_total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
