# Generated by Django 5.2.5 on 2025-08-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_pp', '0005_alter_intermediatedata_contracts_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intermediatedata',
            old_name='okpd2_id',
            new_name='okpd2',
        ),
        migrations.RenameField(
            model_name='intermediatedata',
            old_name='process_id',
            new_name='process',
        ),
    ]
